### ISSUE TITLE
License text formatting

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pyvideoinput#1]
@MichaelBarz The [license](https://github.com/pupil-labs/pyvideoinput/blob/master/LICENSE) should be be plaintext not html.

**Comment by MichaelBarz** [comment]
I formatted it with GitHub markdown. But it seems that the markdown does not apply for the license file. Shall I leave it like that or shall I remove the markdown?

**Comment by willpatera** [comment]
Great! I just added the `.md` file suffix and it now renders appropriately in the browser :smile:
