### ISSUE TITLE
result of get/setParametrs() in videoInput.cpp

### ISSUE THREAD

**Issue by kaiakiy** [pupil-labs/pyvideoinput#2]
@MichaelBarz 
At getParametrs() and setParametrs() in  videoInput.cpp, the conditional branches on result code appear strange for me.
I guess "VIDEOINPUT: Parametrs of the video device cannot be gotten!!!" should be logged if ResultCode is not OK. --Am I wrong?

**Comment by MichaelBarz** [comment]
Hi, this project is a wrapper for an existing library only. You might address your concerns here: http://www.codeproject.com/Articles/776058/Capturing-Live-video-from-Web-camera-on-Windows-an .
In case that changes are made to the library we'll of course consider to update our wrapper.

**Comment by kaiakiy** [comment]
I couldn't find the source code in that site, but now I find it. Yes, they are exactly the same. Thank you for your advice.
